### ISSUE TITLE
Failin to run with the opensource Ubuntu swift version.

### ISSUE THREAD

**Issue by ulanda** [AE9RB/SwiftGL#1]
The are several issues like this:
/home/parallels/swift_lab/lab/test/SwiftGL-1.0.0/Sources/Cepoxy.swift:3037:35: error: module 'Cepoxy' has no member named 'epoxy_glViewportIndexedfNV'
public let glViewportIndexedfNV = Cepoxy.epoxy_glViewportIndexedfNV!

And also in the generated code I found errors for almost all the funcrions in the Commands.Swift where the functions are like this:

public func glViewportIndexedfvNV (index index:GLuint, v:UnsafePointer<GLfloat>) {
    glViewportIndexedfvNV(index, v)

An the compiler complains about not having named arguments.

I also tried to run the  Utility/main.swift but also fails to run on my system.

Can you tell me if this is supposed to work or give any hints to fixit.

**Comment by AE9RB** [comment]
You must use Epoxy v1.3.1 (the latest). It must be exactly that version. Your other options are:

1. Generate a new set of SwiftGL files with the gl.xml from the version of Epoxy you are using. 
2. Comment out the missing functions in both Commands and Cepoxy.

I'm investigating ways to remove the "must be exactly Epoxy Vx.x.x" requirement.

**Comment by ulanda** [comment]
But after that (I removed the missing functions), I got the  problem of the "named" arguments.

I tryed to generate the files myself from the xml, but the currnt uploade scrip fails to run on the opensource swift.
[error.log.txt](https://github.com/AE9RB/SwiftGL/files/60216/error.log.txt)

**Comment by AE9RB** [comment]
How is something you comment out giving you an error?

Making the Utility run on other platforms is a separate issue. I have no intention of doing the work for that now because it should fix itself as the core libs mature. But I'd accept a pull request.

I strongly recommend you update to Epoxy 1.3.1. That's the requirement listed in the README.

**Comment by ulanda** [comment]
Ok, after upgrading Epoxy, I still get the named arguments error, I think its related to my swift version.

parallels@ubuntu:~/swift_lab/lab/test/Demo$ swift --version
Swift version 2.2-dev (LLVM 46be9ff861, Clang 4deb154edc, Swift 778f82939c)
Target: x86_64-unknown-linux-gnu

I'm attaching  the compilation errors.

[error2.txt](https://github.com/AE9RB/SwiftGL/files/60241/error2.txt)

Thanks for your support

**Comment by AE9RB** [comment]
The "missing argument labels" error is because you still have things commented out in Cepoxy. You can not comment out functions in Cepoxy and leave them in Commands.

**Comment by AE9RB** [comment]
Epoxy no longer required as of v1.0.1
